server:
  port: ${SHOP_SERVER_PORT:8081}

spring:
  application:
    name: shop-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${SHOP_DB_URL:jdbc:sqlite:./b2c_mall_shop.db}

mybatis:
  mapper-locations: classpath:mapper/*.xml
