server:
  port: ${GATEWAY_SERVER_PORT:8080}

spring:
  application:
    name: gate-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
    gateway:
      routes:
        # 👉 shop服务路由
        - id: shop
          uri: lb://shop-service
          predicates:
            - Path=/api/shop/**
          filters:
            - StripPrefix=1  # 去掉第一层前缀 /api
